# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Services": "00_cli.ipynb",
         "Pipeline": "00_cli.ipynb",
         "cfe_cli": "00_cli.ipynb",
         "LinodeAPI": "01_services_01_linode.ipynb"}

modules = ["cli.py",
           "services/linode.py"]

doc_url = "https://codingforentrepreneurs.github.io/cfe/"

git_url = "https://github.com/jmitchel3/cfe/tree/main/"

def custom_doc_links(name): return None
