# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_cli.ipynb (unless otherwise specified).

__all__ = ['Services', 'Pipeline', 'cfe_cli']

# Cell
from .services import linode
import fire

class Services(object):

    def __init__(self):
        self.linode = linode.LinodeAPI


class Pipeline(object):
    def __init__(self):
        self.services = Services()


def cfe_cli():
    fire.Fire(Pipeline)