# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_cli.ipynb (unless otherwise specified).

__all__ = ['Services', 'Pipeline', 'cfe_cli']

# Cell
from .tools import security
from .services import linode
import fire

class Services(object):

    def __init__(self):
        self.linode = linode.LinodeAPI


class _New(object):
    def __init__(self):
        self.secret = security.get_new_secret

class Pipeline(object):
    def __init__(self):
        self.services = Services()
        self.new = _New()


def cfe_cli():
    fire.Fire(Pipeline)